name = "learncard-ocr"
account_id = "b75be94e1adc9a5010d095f86a3c5ace"
main = "src/index.js"
compatibility_date = "2026-01-24"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "OCR_LIMITS"
id = "39959b76a26bb91378f24590f4c7"
